### ISSUE TITLE
Stable Picture-In-Picture mode

### ISSUE THREAD

**Issue by msp-ampcome** [calvinckho/capacitor-jitsi-meet#67] opened 2021-12-30 10:14 UTC
Hey, Hope you are doing well. We are trying to use the PIP mode. But once we enter the pip mode, we can interact with the app without any issues but video and audio become very unstable/glitchy. is there any way to stabilize this issue. Because in the jitsi meet app, the pip mode is working fine. Please let us know if there is any solution. Thank you for creating this plugin.

**Comment by jefaokpta** [comment] 2021-12-30 14:36
Have you tested the pip on Android or IOS? If it's on Android, did you need to change something in the native code?

**Comment by msp-ampcome** [comment] 2021-12-31 03:55
It is on android. I have to change the AndroidManifest in the plugin to enable PIP. but once enabled, going in and out of PIP is very jarring experience. but it working on jitsi meet app and flutter plugin.

**Comment by jefaokpta** [comment] 2022-01-03 15:13
> It is on android. I have to change the AndroidManifest in the plugin to enable PIP. but once enabled, going in and out of PIP is very jarring experience. but it working on jitsi meet app and flutter plugin.

I had the same experience, on native code and in flutter works pretty well. Even with this issue I rather Ionic than others. It's more simple.

**Comment by calvinckho** [comment] 2022-01-03 15:26
I intentionally disabled PIP on the plugin for this reason. I will investigate again and see if there is any solution.

**Comment by calvinckho** [comment] 2022-01-04 02:26
@jefaokpta @msp-ampcome According to the [Jitsi mobile SDK documentation](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#picture-in-picture):

`Jitsi Meet SDK does not currently implement native Picture-in-Picture on iOS. If desired, apps need to implement non-native Picture-in-Picture themselves and resize JitsiMeetView.`

I currently do not have time to work on this, but you are welcome to try and add non-native support for PIP in iOS and submit a PR.

As for PIP support on Android, I have done some work and seem to be able to get it to work. Try to install 2.1.2-beta.0 and deploy it on Android to test it.

**Comment by msp-ampcome** [comment] 2022-01-04 03:16
@calvinckho Hey thanks for the quick update, I installed the beta version and tested it. Now PIP mode is working properly, Audio/Video is working as expected. But If i disconnect the call, the app is crashing, regardless of whether i entered PIP mode or not. This is the error I am getting

E/JitsiMeetSDK: JitsiMeetUncaughtExceptionHandler FATAL ERROR
    java.lang.RuntimeException: Unable to stop activity {com.kr4all.doctorapp/com.capacitor.jitsi.plugin.JitsiActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jitsi.meet.sdk.JitsiMeetView.dispose()' on a null object reference
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4956)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4927)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5001)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7904)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jitsi.meet.sdk.JitsiMeetView.dispose()' on a null object reference
        at com.capacitor.jitsi.plugin.JitsiActivity.onStop(JitsiActivity.java:162)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1477)
        at android.app.Activity.performStop(Activity.java:8358)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4948)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4927) 
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5001) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:7904) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
    
    java.lang.RuntimeException: Unable to stop activity {com.kr4all.doctorapp/com.capacitor.jitsi.plugin.JitsiActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jitsi.meet.sdk.JitsiMeetView.dispose()' on a null object reference
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4956)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4927)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5001)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7904)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.jitsi.meet.sdk.JitsiMeetView.dispose()' on a null object reference
        at com.capacitor.jitsi.plugin.JitsiActivity.onStop(JitsiActivity.java:162)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1477)
        at android.app.Activity.performStop(Activity.java:8358)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4948)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4927) 
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5001) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:233) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2116) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:7904) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
I/JitsiMeetSDK: [features/base/connection] No connection found while disconnecting.
    [FeatureFlags] Source name signaling: false
D/JitsiMeetSDK: [modules/connectivity/NetworkInfo.js] updateNetworkInfo { isOnline: true }
I/JitsiMeetSDK: [features/analytics] Initialized 1 analytics handlers
I/JitsiMeetSDK: [features/base/media] Start muted: 
D/JitsiMeetSDK: ExternalAPI Sending event: VIDEO_MUTED_CHANGED with data: { NativeMap: {"muted":0} }
I/JitsiMeetSDK: [features/base/media] Start audio only set to false

**Comment by calvinckho** [comment] 2022-01-04 03:35
can you try 2.1.2-beta.1? I fixed a bug which caused the crash.

**Comment by msp-ampcome** [comment] 2022-01-04 03:37
Will try and let you know

**Comment by msp-ampcome** [comment] 2022-01-04 03:48
@calvinckho Yeah, now the crash is fixed. Thank you so much. We really appreciate your quick response and your hard work. I tested it on Android 11. We will test it on more devices and let you know the results.

**Comment by msp-ampcome** [comment] 2022-01-04 07:05
@calvinckho sometimes the status bar is showing up on PIP mode. like this https://ibb.co/GCK0ss8

**Comment by calvinckho** [comment] 2022-01-06 00:46
@msp-ampcome Thanks for your research. It was helpful. I disabled the header bar in the plugin's AndroidMannifest.xml file. Please try 2.1.2-beta.2 in your test app.

**Comment by msp-ampcome** [comment] 2022-01-08 04:33
@calvinckho Thanks for the update, We tested it, now the header bar is not coming. But we found an another bug. if the user closed the PIP window with the close button. the call is not disconnected on jitsi. if you rejoin the call. you can see 3 participants. You can see your name twice. one is current session, another one is the previous dead version. This issue is not coming, if we disconnect from the meeting properly via the reject call button on the expanded jitsi view.

**Comment by calvinckho** [comment] 2022-01-09 17:32
Ok let me check on this issue.

**Comment by msp-ampcome** [comment] 2022-01-19 11:43
@calvinckho We started testing our app on iOS(not PIP just the video call). but when using the beta. The app is crashing when we tried to initiate the video call.

**Comment by calvinckho** [comment] 2022-01-20 20:42
Ok thanks for reporting this issue on iOS. I had been busy but will try to debug it soon.

**Comment by calvinckho** [comment] 2022-01-29 06:33
@msp-ampcome I cannot reproduce the crash. What was the last known beta version that works?

**Comment by msp-ampcome** [comment] 2022-01-29 06:39
@calvinckho Apologies, We were able to fix the issue. we missed a config on xcode. I am extremely sorry that i haven't updated the feedback. I got busy with other things.

**Comment by calvinckho** [comment] 2022-01-29 17:22
> @calvinckho Thanks for the update, We tested it, now the header bar is not coming. But we found an another bug. if the user closed the PIP window with the close button. the call is not disconnected on jitsi. if you rejoin the call. you can see 3 participants. You can see your name twice. one is current session, another one is the previous dead version. This issue is not coming, if we disconnect from the meeting properly via the reject call button on the expanded jitsi view.

OK. also want to check if this issue is still experienced when you use 2.1.2-beta.2 in Android?

**Comment by calvinckho** [comment] 2022-02-05 02:05
> > @calvinckho Thanks for the update, We tested it, now the header bar is not coming. But we found an another bug. if the user closed the PIP window with the close button. the call is not disconnected on jitsi. if you rejoin the call. you can see 3 participants. You can see your name twice. one is current session, another one is the previous dead version. This issue is not coming, if we disconnect from the meeting properly via the reject call button on the expanded jitsi view.
> 
> OK. also want to check if this issue is still experienced when you use 2.1.2-beta.2 in Android?

I have tried to reproduce this bug. It tried to open and close the PIP window about 15 times. Out of the 15 times, only 1 time did it fail to leave the call. The other 14 times it was able to leave the call. 

Perhaps it is a race condition? But as I was not able to reproduce the issue, it is very difficult to debug it. Also, I cannot merge it with the main branch until this issue is resolved.

**Comment by calvinckho** [comment] 2022-02-09 03:21
2.1.2 is released with the PiP mode disabled because of the instability reported above. For future testing purposes, you can install 2.1.2+ and do the follow to enable PIP mode for Android:

1. In Capacitor-Jitsi-Meet's AndroidManifest.xml, set android:supportsPictureInPicture="true"
2. In JitsiActivity.java, uncomment the onStop() handler code (line 170 - 179).

Things to test and report:
- Please let me know if you experience any issue with closing the PIP window manually. 
- The issue has been reported, but it was difficult to reproduce as it does not happen consistently. It can be due to race condition or other unknown causes.

**Closed by calvinckho** 2022-02-09 03:21 UTC

**Comment by calvinckho** [comment] 2022-03-05 07:32
> > > @calvinckho Thanks for the update, We tested it, now the header bar is not coming. But we found an another bug. if the user closed the PIP window with the close button. the call is not disconnected on jitsi. if you rejoin the call. you can see 3 participants. You can see your name twice. one is current session, another one is the previous dead version. This issue is not coming, if we disconnect from the meeting properly via the reject call button on the expanded jitsi view.

PIP in Android is now fully supported in the 2.2.0 release. The bug mentioned above should be fixed. To enable PIP in Android:

i. In the plugin's AndroidManifest.xml, set supportsPictureInPicture to true (default). To disable PIP, you must change the setting back to false.
```
android:supportsPictureInPicture="true"
```
ii. Set the featureFlags param 'pip.enabled' to true
```
featureFlags: { 'pip.enabled': true }
```

For iOS PIP implementation, as the Jitsi SDK doesn't support native PIP yet, for those who need it in their iOS deployment, I offer consultation service to help you implement it in a non-native way. See this video for a demo:

https://user-images.githubusercontent.com/23274587/156873247-0e27b5aa-1212-444a-a442-6da94041bc76.MP4

Feel free to [DM me](mailto:ch235@cornell.edu) for more info.
