### ISSUE TITLE
issue with android

### ISSUE THREAD

**Issue by sumeshd** [calvinckho/capacitor-jitsi-meet#19] opened 2020-07-31 19:51 UTC
I have followed instructions as I read MD and followed all 3 steps.
Then followed up with the Jitsi Meet android deployment documentation. However I see issues happening can you help me build this right. 

![Screenshot_100](https://user-images.githubusercontent.com/12375007/89070759-15588f00-d393-11ea-89c7-cb17124a81d5.png)

**Comment by calvinckho** [comment] 2020-07-31 19:52
Duplicate of #18

**Closed by calvinckho** 2020-07-31 19:52 UTC
