### ISSUE TITLE
JitsiMeetSDK: [features/mobile/pip] Error entering PiP mode: Error: enterPictureInPictureMode: Current activity does not support picture-in-picture.

### ISSUE THREAD

**Issue by vaibhavphutane** [calvinckho/capacitor-jitsi-meet#59] opened 2021-09-13 17:11 UTC
I am getting the above issue while working with PIP mode,

Device: One Plus 7 
OS: Oxygen OS
Android:: 10

I have configured the following activity in AndroidMainfest.xml

`<activity
         android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:resizeableActivity="true"
            android:supportsPictureInPicture="true"
            android:windowSoftInputMode="adjustResize"
            android:launchMode="singleTask">`

**Comment by calvinckho** [comment] 2021-09-13 22:32
Jitsi Meet SDK does not currently implement native Picture-in-Picture on iOS. If desired, apps need to implement non-native Picture-in-Picture themselves and resize JitsiMeetView. Please see the official SDK documentation on this. https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#picture-in-picture

**Comment by calvinckho** [comment] 2021-09-13 22:51
Hi @vaibhavphutane, I had to turn off PIP in my android app, because we tried to turn it on, but it doesn't perform as desired. https://github.com/calvinckho/capacitor-jitsi-meet/issues/20#issuecomment-668286135

As to your particular issue, it is hard for me to reproduce it. But I was able to get the PIP partially working on my Samsung S7 about a year ago as referenced above.

**Comment by vaibhavphutane** [comment] 2021-09-14 06:22
Hi @calvinckho Ah ok, I was trying to debug the android application  found the following
In picture in picture module `PictureInPictureModule.class` `isSupported` is flag is true that means I have device support for PIP however it fails at below line of code
` Builder builder = (new Builder()).setAspectRatio(new Rational(1, 1));
                    if (!currentActivity.enterPictureInPictureMode(builder.build())) {
                        throw new RuntimeException("Failed to enter Picture-in-Picture");
                    }`
 If I further debug It seems that its failing to get activity support in `Activity.java `file
 `public static IActivityTaskManager getService() {
        return IActivityTaskManagerSingleton.get();
    }

    @UnsupportedAppUsage(trackingBug = 129726065)
    private static final Singleton<IActivityTaskManager> IActivityTaskManagerSingleton =
            new Singleton<IActivityTaskManager>() {
                @Override
                protected IActivityTaskManager create() {
                    final IBinder b = ServiceManager.getService(Context.ACTIVITY_TASK_SERVICE);
                    return IActivityTaskManager.Stub.asInterface(b);
                }
            };
`

**Comment by calvinckho** [comment] 2021-09-18 20:00
Hi @vaibhavphutane. Since it involves error messages in the SDK, the best place is to discuss in the jitsi-meet repo. See the identical issue discussed there: https://github.com/jitsi/jitsi-meet/issues/8247. I will close this for now.

**Closed by calvinckho** 2021-09-18 20:00 UTC

**Comment by calvinckho** [comment] 2022-03-05 07:36
PIP in Android is now fully supported in 2.2.0. https://github.com/calvinckho/capacitor-jitsi-meet/issues/67#issuecomment-1059713128
