### ISSUE TITLE
Language Option

### ISSUE THREAD

**Issue by gasci** [calvinckho/capacitor-jitsi-meet#93] opened 2024-01-15 19:52 UTC
Thank you for this great plugin.

Is there an option to adjust the interface language?

I used the `lang` parameter but it doesn't work unfortunately.

**Comment by calvinckho** [comment] 2024-01-15 20:18
@gasci Can you try in configOverride, use the property defaultLanguage instead of lang?

Referencing config.js line 360
// Default language for the user interface.
    // defaultLanguage: 'en',

**Comment by gasci** [comment] 2024-01-15 21:58
```
 const result = await Jitsi.joinConference({
        roomName: "meeting-tester",
        url: "https://meet.jit.si",
        displayName: "Full Name",
        subject: "Meeting",
        startWithAudioMuted: false,
        featureFlags: {
          "recording.enabled": false,
          "live-streaming.enabled": false,
          "android.screensharing.enabled": false,
        },
        configOverrides: { defaultLanguage: "tr" },
      });
```

This configuration didn't work. It is supposed to make the default language Turkish.

**Comment by calvinckho** [comment] 2024-01-16 00:58
I did some research on the jitsi-meet source code and found the following:

1. The configOverrides property [only works on web browser](https://github.com/jitsi/jitsi-meet/blob/b52b4c2a78acc23395c1441c9ff656fc636efbf5/react/features/base/i18n/languageDetector.web.ts)
2. on mobile SDKs, the [LanguageDetector](https://github.com/jitsi/jitsi-meet/blob/a6f93db8e343c95cda17e8fc7b7fe0491acd2805/react/features/base/i18n/languageDetector.native.ts) is hardcoded to detect the mobile device system language, and ignore the config.js overrides.
3. I have tested this on iOS. If you change the iOS system language, Jitsi would use it as the default language for the UI until the user changes it manually, and the language choice is then cached.

If this is a mission critical feature, I can help you custom-build the mobile SDKs (of your choice of Capacitor version) that has the language of your choice hard-coded into it. [DM](mailto:ch235@cornell.edu) me to discuss more.

I will close this as it is not a bug related to my plugin. It has to do with the jitsi-meet source code.

**Closed by calvinckho** 2024-01-16 00:58 UTC

**Comment by gasci** [comment] 2024-01-16 08:14
Hi, [calvinckho](https://github.com/calvinckho).

It is not a mission critical feature actually. Having the system language is enough at this moment. But thank you for your quick responses. It is a good feeling to see that this repo is actively being maintained.
