### ISSUE TITLE
Compatibility with Swift Language Version: 5.0

### ISSUE THREAD

**Issue by polfernandez** [calvinckho/capacitor-jitsi-meet#79] opened 2022-07-19 08:36 UTC
It turns that with Swift Language Version: 5.0 (iOS XCode) it doesn't compile.

**Comment by calvinckho** [comment] 2022-08-01 19:33
Maybe this is an issue with Xcode 13.4.1? I still have 13.3 and I can compile with Swift 5 and run on iPhone 12 and 13 simulators.

Since I can't reproduce this issue, I will close it for now. I will reopen it if it fails on 13.4.1 or later version and is proved to be caused by the newer version of Xcode.

**Closed by calvinckho** 2022-08-01 19:33 UTC

**Comment by abennouna** [comment] 2022-08-17 16:19
In case it helps, I am on Xcode 13.4.1 and build succeeds with Swift Language Version: **Swift 5** (it's the setting that I already had)

I followed all the instructions in the readme. Only no. 6 and 8. were necessary:

6. Turn off Bitcode in the app target as well as the pod targets. In xcode Project Navigator (...)
8. In order for app to properly work in the background, select the "audio" and "voip" background modes (...)
